---
# tasks file for rhao.nginx
    - name: Install Nginx
      apt: name=nginx state=installed
    - name: Start Nginx
      service: name=nginx state=started
    - name: Create Nginx config
      template: src=default dest=/etc/nginx/sites-available/default
      notify: restart nginx

