---
- hosts: all
  roles:
    - role: rhao.wordpress
      database_name: rhaowp
      database_user: rhaowp
      database_password: bananas18374
      wp_domain: book.example.com
      initial_post_title: Hey There
      initial_post_content: >
       This is an example post. Change me to say something interesting.
  become: true
  tasks:
    - name: Make sure that we can connect to the mahcine
      ping:





